#rakefile.rb

task :default => [:generate]

task :generate => :clear do
    sh 'jekyll'
end

task :clear do
    sh 'rm -rf _site/*'
end

task :deploy do
    sh 'rsync -n -avz --progress --rsh="ssh -p22123" _site/ hertze@hertze.com:~/public_html'
end